import { Activity, CircleAlert } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { getDurableOperationExceptions, getDurableOperationHistory, getDurableOperations } from "@/lib/admin-v2-client";
import { AdminEmptyState, AdminErrorState, AdminLoadingState, AdminPageHeader, AdminSection, StatusBadge, TableFrame, formatAdminDate } from "../components/AdminUi";
import { adminQueryKeys, useAdminReadQuery } from "../data/admin-queries";

function OperationsList() {
  const operations = useAdminReadQuery(adminQueryKeys.operations, () => getDurableOperations(50));
  const exceptions = useAdminReadQuery(adminQueryKeys.exceptions, () => getDurableOperationExceptions(50));
  return <div className="space-y-6"><AdminSection title="Generation operations" description="A compact execution and financial state view. Retry, refund and reconciliation actions remain unavailable until typed commands are added.">{operations.isLoading ? <AdminLoadingState /> : operations.isError ? <AdminErrorState message="Operations could not be loaded." onRetry={() => void operations.refetch()} /> : operations.data?.length ? <TableFrame><thead className="border-b border-white/[0.08] bg-white/[0.025] text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-medium">Operation</th><th className="py-3 font-medium">Provider</th><th className="py-3 font-medium">Customer charge</th><th className="py-3 font-medium">State</th><th className="px-5 py-3 font-medium">Updated</th></tr></thead><tbody>{operations.data.map((operation) => <tr key={operation.operationId} className="border-b border-white/[0.06] last:border-0"><td className="max-w-72 px-5 py-3"><Link to={`/admin/operations/${encodeURIComponent(operation.operationId)}`} className="block truncate font-medium text-violet-200 hover:text-violet-100">{operation.operationId}</Link><p className="mt-0.5 truncate text-xs text-slate-500">{operation.ownerId}</p></td><td className="py-3 text-sm text-slate-300">{operation.providerId ?? "—"}</td><td className="py-3 text-sm text-slate-300">{operation.customerCredits} credits</td><td className="py-3"><StatusBadge status={operation.state} /></td><td className="px-5 py-3 text-xs text-slate-500">{formatAdminDate(operation.updatedAt)}</td></tr>)}</tbody></TableFrame> : <AdminEmptyState title="No operations recorded" description="Durable generation activity will appear here once it is created by the engine." icon={Activity} />}</AdminSection><AdminSection title="Needs review" description="Exceptions remain evidence-first; this page does not retry, refund or release anything.">{exceptions.isLoading ? <AdminLoadingState rows={3} /> : exceptions.isError ? <AdminErrorState message="Exceptions could not be loaded." onRetry={() => void exceptions.refetch()} /> : exceptions.data?.length ? <div className="divide-y divide-white/[0.06]">{exceptions.data.map((exception) => <Link key={`${exception.category}:${exception.operationId}`} to={`/admin/operations/${encodeURIComponent(exception.operationId)}`} className="block px-5 py-4 transition hover:bg-white/[0.025]"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-medium text-white">{exception.category.replace(/_/g, " ")}</p><StatusBadge status="RECONCILIATION_REQUIRED" /></div><p className="mt-2 text-xs leading-5 text-slate-400">{exception.reason}</p></Link>)}</div> : <AdminEmptyState title="No exceptions pending" description="The current durable runtime has no unresolved exception records." icon={CircleAlert} />}</AdminSection></div>;
}

function OperationDetail() {
  const { operationId = "" } = useParams();
  const history = useAdminReadQuery(["admin", "operation", operationId], () => getDurableOperationHistory(operationId));
  if (history.isLoading) return <AdminLoadingState rows={5} />;
  if (history.isError) return <AdminErrorState message="The operation history could not be loaded." onRetry={() => void history.refetch()} />;
  if (!history.data) return <AdminEmptyState title="Operation not found" description="No durable operation matches this reference." />;
  const operation = history.data.operation;
  return <div className="space-y-6"><AdminPageHeader eyebrow="OPERATIONS" title="Operation detail" description="Execution, reservation and provider evidence are read-only in the current environment." action={<Link to="/admin/operations" className="text-sm font-medium text-violet-200 hover:text-violet-100">Back to operations</Link>} /><div className="grid gap-6 xl:grid-cols-2"><AdminSection title="Overview"><dl className="grid gap-4 p-5 sm:grid-cols-2"><Detail label="Operation" value={operation.id} /><Detail label="State" value={operation.state} /><Detail label="Customer charge" value={`${operation.customer_credits} credits`} /><Detail label="Updated" value={formatAdminDate(operation.updated_at)} /></dl></AdminSection><AdminSection title="Financial state"><dl className="grid gap-4 p-5 sm:grid-cols-2"><Detail label="Reservation" value={history.data.reservation ? `${history.data.reservation.state} · held ${history.data.reservation.held_credits}` : "No reservation"} /><Detail label="Provider cost" value={history.data.providerCostOutcome ? `${history.data.providerCostOutcome.provider_credits} credits` : "No actual cost evidence"} /></dl></AdminSection></div><AdminSection title="Timeline" description="Recorded state events."><div className="divide-y divide-white/[0.06]">{history.data.events.length ? history.data.events.map((event) => <div key={`${event.sequence}:${event.event_name}`} className="flex items-center justify-between gap-4 px-5 py-3"><div><p className="text-sm font-medium text-white">{event.event_name}</p><p className="mt-1 text-xs text-slate-500">State {event.state} · v{event.state_version}</p></div><span className="text-xs text-slate-500">#{event.sequence}</span></div>) : <AdminEmptyState title="No events" description="No state events are stored for this operation." />}</div></AdminSection></div>;
}

function Detail({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-white/[0.08] bg-[#0b0d10] p-4"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-2 break-words text-sm text-slate-200">{value}</dd></div>; }

export default function AdminOperationsPage() {
  const { operationId } = useParams();
  return <div className="space-y-6">{operationId ? <OperationDetail /> : <><AdminPageHeader eyebrow="MONITORING" title="Operations" description="Monitor generation execution, customer credit settlement and evidence-first exceptions." /><OperationsList /></>}</div>;
}
