import { ArrowLeft, CalendarDays, CircleDollarSign, History, Search, ShieldCheck, UserRound, UsersRound, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getProductionCustomerDetail, getProductionCustomers } from "@/lib/admin-v2-client";
import { AdminEmptyState, AdminErrorState, AdminLoadingState, AdminPageHeader, AdminSection, MetricCard, StatusBadge, TableFrame, formatAdminDate, toTitle } from "../components/AdminUi";
import { adminQueryKeys, useAdminReadQuery } from "../data/admin-queries";

const credits = (value: number) => new Intl.NumberFormat("en-US").format(value);

function CustomerDetail({ ownerId }: { ownerId: string }) {
  const customer = useAdminReadQuery(adminQueryKeys.customer(ownerId), () => getProductionCustomerDetail(ownerId));
  if (customer.isLoading) return <AdminLoadingState rows={8} />;
  if (customer.isError || !customer.data) return <AdminErrorState message="The customer account could not be loaded." onRetry={() => void customer.refetch()} />;
  const data = customer.data;
  const activeSubscription = data.subscriptions.find((subscription) => subscription.state === "ACTIVE") ?? data.subscriptions[0];
  return <div className="space-y-6">
    <AdminPageHeader eyebrow="CUSTOMER" title={data.profile?.displayName || data.profile?.email || "Customer account"} description="Identity, subscription, wallet and immutable financial activity in one account view." action={<Link to="/admin/users" className="inline-flex h-10 items-center gap-2 rounded-lg border border-white/[0.1] px-3 text-sm font-medium text-white transition hover:bg-white/[0.05]"><ArrowLeft className="h-4 w-4" />All users</Link>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard icon={WalletCards} label="Available credits" value={credits(data.wallet?.availableCredits ?? 0)} note={`${credits(data.wallet?.heldCredits ?? 0)} held · ${credits(data.wallet?.spentCredits ?? 0)} spent`} tone="success" />
      <MetricCard icon={CalendarDays} label="Subscription" value={activeSubscription?.displayName ?? "None"} note={activeSubscription ? `${toTitle(activeSubscription.state)} · ends ${new Date(activeSubscription.currentPeriodEnd).toLocaleDateString()}` : "No subscription period"} />
      <MetricCard icon={History} label="Generations" value={String(data.operations.length)} note={`${data.operations.filter((item) => item.state === "SETTLED").length} settled in recent history`} />
      <MetricCard icon={ShieldCheck} label="Account status" value={toTitle(data.lifecycle)} note={data.profile?.authProvider ? `Signed in with ${data.profile.authProvider}` : "Finance-only identity"} tone={data.lifecycle === "ACTIVE" ? "success" : "attention"} />
    </div>
    <AdminSection title="Account" description="Supabase Auth identity and server-owned account facts.">
      <dl className="grid gap-px bg-white/[0.08] sm:grid-cols-2 xl:grid-cols-4">{[["Email", data.profile?.email ?? "Not available"], ["User ID", data.ownerId], ["Joined", formatAdminDate(data.profile?.createdAt)], ["Last sign-in", formatAdminDate(data.profile?.lastSignInAt)]].map(([label, value]) => <div key={label} className="min-w-0 bg-[#12161b] p-4"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-2 truncate text-sm font-medium text-white" title={value}>{value}</dd></div>)}</dl>
    </AdminSection>
    <div className="grid gap-6 xl:grid-cols-2">
      <AdminSection title="Subscription history" description="Every assigned plan version and billing period.">{data.subscriptions.length ? <div className="divide-y divide-white/[0.07]">{data.subscriptions.map((subscription) => <article key={subscription.id} className="flex items-center justify-between gap-4 p-4"><div><p className="font-medium text-white">{subscription.displayName}</p><p className="mt-1 text-xs text-slate-500">{credits(subscription.creditsPerPeriod)} credits · {subscription.interval.toLowerCase()} · {new Date(subscription.currentPeriodStart).toLocaleDateString()}–{new Date(subscription.currentPeriodEnd).toLocaleDateString()}</p></div><StatusBadge status={subscription.state} /></article>)}</div> : <AdminEmptyState title="No subscription" description="This user has no subscription period yet." />}</AdminSection>
      <AdminSection title="Credit ledger" description="Recent immutable entries affecting this customer's credit accounts.">{data.ledgerActivity.length ? <div className="divide-y divide-white/[0.07]">{data.ledgerActivity.slice(0, 10).map((entry) => <article key={entry.journalId} className="flex items-center justify-between gap-4 p-4"><div><p className="text-sm font-medium text-white">{toTitle(entry.reasonCode)}</p><p className="mt-1 text-xs text-slate-500">{formatAdminDate(entry.createdAt)} · {entry.kind}</p></div><span className={`text-sm font-semibold ${entry.creditDelta > 0 ? "text-emerald-300" : entry.creditDelta < 0 ? "text-rose-300" : "text-slate-400"}`}>{entry.creditDelta > 0 ? "+" : ""}{credits(entry.creditDelta)}</span></article>)}</div> : <AdminEmptyState title="No ledger activity" description="Credit grants, holds, captures and refunds will appear here." />}</AdminSection>
    </div>
    <AdminSection title="Generation history" description="Recent operations with their exact Engine state and customer-credit amount.">{data.operations.length ? <TableFrame><thead className="border-b border-white/[0.08] bg-white/[0.025] text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-medium">Operation</th><th className="py-3 font-medium">Credits</th><th className="py-3 font-medium">Status</th><th className="px-5 py-3 font-medium">Updated</th></tr></thead><tbody>{data.operations.map((operation) => <tr key={operation.operationId} className="border-b border-white/[0.06] last:border-0"><td className="max-w-72 px-5 py-3 font-mono text-xs text-slate-300">{operation.operationId}</td><td className="py-3 text-sm text-white">{credits(operation.customerCredits)}</td><td className="py-3"><StatusBadge status={operation.state} /></td><td className="px-5 py-3 text-xs text-slate-500">{formatAdminDate(operation.updatedAt)}</td></tr>)}</tbody></TableFrame> : <AdminEmptyState title="No generations" description="This customer has not submitted a generation operation." />}</AdminSection>
  </div>;
}

export default function AdminUsersPage() {
  const { userId } = useParams();
  const customers = useAdminReadQuery(adminQueryKeys.customers, getProductionCustomers);
  const [search, setSearch] = useState("");
  const rows = useMemo(() => { const term = search.trim().toLowerCase(); return (customers.data ?? []).filter((customer) => !term || [customer.email, customer.displayName, customer.ownerId, customer.subscription?.displayName].some((value) => value?.toLowerCase().includes(term))); }, [customers.data, search]);
  if (userId) return <CustomerDetail ownerId={userId} />;
  const activeSubscribers = (customers.data ?? []).filter((customer) => customer.subscription?.state === "ACTIVE").length;
  const totalAvailable = (customers.data ?? []).reduce((sum, customer) => sum + (customer.wallet?.availableCredits ?? 0), 0);
  return <div className="space-y-6">
    <AdminPageHeader eyebrow="BUSINESS" title="Users" description="Real Supabase accounts joined with subscriptions, wallets and generation activity." />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={UsersRound} label="Registered users" value={String(customers.data?.length ?? 0)} note="Supabase Auth directory" /><MetricCard icon={CalendarDays} label="Active subscribers" value={String(activeSubscribers)} note="Current active periods" tone="success" /><MetricCard icon={CircleDollarSign} label="Available credits" value={credits(totalAvailable)} note="Across customer wallets" /><MetricCard icon={ShieldCheck} label="Restricted accounts" value={String((customers.data ?? []).filter((customer) => customer.lifecycle === "BANNED").length)} note="Currently banned" tone="attention" /></div>
    <AdminSection title="Customer directory" description="Search by name, email, user ID or subscription plan.">
      <div className="flex flex-col gap-3 border-b border-white/[0.08] p-4 sm:flex-row sm:items-center sm:justify-between"><label className="relative block w-full sm:max-w-sm"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search users" className="h-10 w-full rounded-lg border border-white/[0.1] bg-[#0b0d10] pl-9 pr-3 text-sm text-white outline-none transition placeholder:text-slate-600 focus:border-violet-400/60 focus:ring-2 focus:ring-violet-400/20" /></label><span className="text-xs text-slate-500">{rows.length} users</span></div>
      {customers.isLoading ? <AdminLoadingState /> : customers.isError ? <AdminErrorState message="The Production customer directory could not be loaded." onRetry={() => void customers.refetch()} /> : rows.length ? <TableFrame><thead className="border-b border-white/[0.08] bg-white/[0.025] text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-medium">Customer</th><th className="py-3 font-medium">Subscription</th><th className="py-3 font-medium">Wallet</th><th className="py-3 font-medium">Usage</th><th className="px-5 py-3 font-medium">Status</th></tr></thead><tbody>{rows.map((customer) => <tr key={customer.ownerId} className="border-b border-white/[0.06] transition last:border-0 hover:bg-white/[0.025]"><td className="max-w-80 px-5 py-3"><Link to={`/admin/users/${encodeURIComponent(customer.ownerId)}`} className="flex items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg border border-white/[0.08] bg-white/[0.03]"><UserRound className="h-4 w-4 text-violet-300" /></span><span className="min-w-0"><span className="block truncate font-medium text-white">{customer.displayName || customer.email || "Unnamed user"}</span><span className="mt-0.5 block truncate text-xs text-slate-500">{customer.email ?? customer.ownerId}</span></span></Link></td><td className="py-3"><p className="text-sm text-slate-200">{customer.subscription?.displayName ?? "No plan"}</p><p className="mt-0.5 text-xs text-slate-500">{customer.subscription ? toTitle(customer.subscription.state) : "Registered only"}</p></td><td className="py-3"><p className="text-sm font-medium text-white">{credits(customer.wallet?.availableCredits ?? 0)}</p><p className="mt-0.5 text-xs text-slate-500">{credits(customer.wallet?.spentCredits ?? 0)} spent</p></td><td className="py-3 text-sm text-slate-400">{customer.operationCount} total · {customer.activeOperationCount} active</td><td className="px-5 py-3"><StatusBadge status={customer.lifecycle} /></td></tr>)}</tbody></TableFrame> : <AdminEmptyState title={customers.data?.length ? "No matching users" : "No registered users"} description={customers.data?.length ? "Try a different search term." : "Supabase Auth users will appear here after registration."} />}
    </AdminSection>
  </div>;
}
